reformat

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,11 +1,1 @@
-#!/bin/sh
-. "$(dirname $0)/_/husky.sh"
-
-set +e
-yarn -s ng-dev format staged 2>/dev/null
-if [ $? -ne 0 ]; then
-  echo "WARNING: failed to run file formatting (ng-dev format staged)"
-fi
-
-
-exit 0;
+#!/bin/sh. "$(dirname $0)/_/husky.sh"set +eyarn -s ng-dev format staged 2>/dev/nullif [ $? -ne 0 ]; then  echo "WARNING: failed to run file formatting (ng-dev format staged)"fiexit 0;
diff --git a/.husky/prepare-commit-msg b/.husky/prepare-commit-msg
--- a/.husky/prepare-commit-msg
+++ b/.husky/prepare-commit-msg
@@ -1,11 +1,1 @@
-#!/bin/sh
-. "$(dirname $0)/_/husky.sh"
-
-set +e
-
-yarn -s ng-dev commit-message restore-commit-message-draft $1 $2 2>/dev/null
-if [ $? -ne 0 ]; then
-  echo "WARNING: failed to attempt to restore commit message draft (ng-dev commit-message restore-commit-message-draft)"
-fi
-
-exit 0;
+#!/bin/sh. "$(dirname $0)/_/husky.sh"set +eyarn -s ng-dev commit-message restore-commit-message-draft $1 $2 2>/dev/nullif [ $? -ne 0 ]; then  echo "WARNING: failed to attempt to restore commit message draft (ng-dev commit-message restore-commit-message-draft)"fiexit 0;
